import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { AuthProvider } from "@/components/contextapis/authentication/AuthProvider";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trade Nest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50`}
      >
        <Toaster position="top-center" reverseOrder={false} aria-live="assertive" />

        <SessionProviderWrapper>
          <AuthProvider>
            {/* NavBar */}
            <NavBar />
            <div>{children}</div>
          </AuthProvider>
        </SessionProviderWrapper>
        <Footer />
      </body>
    </html>
  );
}
